name: hello-world-app
description: A Streamlit app that lets users trigger the job included in this bundle.
environment_variables:
  JOB_ID: ${resources.jobs.hello_world.id}
command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0 